# Generated by Django 4.1 on 2022-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0021_alter_driver_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="avatar",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="static/images"
            ),
        ),
    ]
